[package]
name = "ytconvertv2"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
vizia = {git = "https://github.com/vizia/vizia"}
bon = "3.3"
winit = "0.30.9"
rfd = "0.15.2"
platform-dirs = "0.3.0"
nanoserde = "0.1.37"
ffmpeg-sidecar = { version = "2.0.5" }
youtube_dl = { version = "0.10.0", features = ["downloader-native-tls"] }
tokio = { version = "1.44.2", features = ["full"] }
temp-dir = "0.1.14"
fuzzy-matcher = "0.3.7"
open = "5.3.2"
nanoid = "=0.4.0"
thiserror = "2.0.12"
anyhow = "1.0.98"
num-traits = "0.2.19"

[profile.dev]
incremental = true
