name: Build and Release

permissions:
  contents: write

on:
    push:
        tags:
            - v*.*.*

env:
    PYTHON_URL: https://github.com/astral-sh/python-build-standalone/releases/download/20250409/cpython-3.12.10+20250409-x86_64-apple-darwin-pgo+lto-full.tar.zst

jobs:
    build-mac:
        runs-on: macos-13
        steps:
          - name: Grab Version Tag
            uses: nowsprinting/check-version-format-action@v3
            id: version
            with:
                prefix: 'v'

          - name: Checkout Code
            uses: actions/checkout@v4

          - name: Install Rust Toolchain
            uses: actions-rs/toolchain@v1.0.6
            with:
                toolchain: 1.84
        
          - name: Enable Rust Cache
            uses: Swatinem/rust-cache@v2

          - name: Install DotNet SDK
            uses: actions/setup-dotnet@v4
            with:
                dotnet-version: 8.0.x

          - name: Build Release Binary
            run: cargo build --release --features mac-release

          - name: Prep Binary For Packaging
            run: |
                mkdir ./ReleasePrep/
                cp ./target/release/ytconvertv2 ./ReleasePrep/
        
          - name: Download Standalone Python Runtime
            run: |
                mkdir ./PythonPrep/
                mkdir -p ./ReleasePrep/python/bin/
                curl -L ${{ env.PYTHON_URL }} -o PythonPrep/python.tar.zst
                tar --use-compress-program=unzstd -xvf ./PythonPrep/python.tar.zst -C ./PythonPrep/
                cp -Rv ./PythonPrep/python/licenses/ ./ReleasePrep/python/licenses/
                cp -Rv ./PythonPrep/python/install/lib/ ./ReleasePrep/python/lib/
                cp -Lv ./PythonPrep/python/install/bin/python3 ./ReleasePrep/python/bin/python3
          
          - name: Run Velopack
            run: |
                dotnet tool install -g vpk
                vpk pack -u ytconvertv2 -v ${{ steps.version.outputs.full_without_prefix }} -p ./ReleasePrep/ -e ytconvertv2 --delta None --noPortable
                vpk bundle -u ytconvertv2 -v ${{ steps.version.outputs.full_without_prefix }} -p ./ReleasePrep/ -e ytconvertv2 -o ./Bundle/
        
          - name: Modify Assets File
            run: |
                brew install jq
                jq -c 'map(if .Type == "Installer" then .RelativeFileName = "ytconvertv2-osx-Setup.dmg" else . end)' ./Releases/assets.osx.json > ./Releases/tmp
                mv ./Releases/tmp ./Releases/assets.osx.json

          - name: Create DMG Installer
            uses: L-Super/create-dmg-actions@v1.0.3
            with:
                dmg_name: './Releases/ytconvertv2-osx-Setup'
                src_dir: './Bundle/ytconvertv2.app'

          - name: Upload Artifacts
            run: vpk upload github -o ./Releases/ --repoUrl https://github.com/${{ github.repository }} --pre --merge --token ${{ secrets.GITHUB_TOKEN }}

    # build-windows:
    #     runs-on: windows-latest
    #     steps:
    #       - name: Grab Version Tag
    #         uses: nowsprinting/check-version-format-action@v3
    #         id: version
    #         with:
    #             prefix: 'v'

    #       - name: Checkout code
    #         uses: actions/checkout@v4

    #       - name: Install Rust Toolchain
    #         uses: actions-rs/toolchain@v1.0.6
    #         with:
    #             toolchain: 1.84
        
    #       - name: Install DotNet SDK
    #         uses: actions/setup-dotnet@v4
    #         with:
    #             dotnet-version: 8.0.x
        
    #       - name: Build for release
    #         run: cargo build --release

    #       - name: Prep for packaging
    #         run: |
    #             mkdir .\ReleasePrep\
    #             mv .\target\release\ytconvertv2.exe .\ReleasePrep\ytconvertv2.exe

    #       - name: Run Velopack
    #         run: |
    #             dotnet tool install -g vpk
    #             vpk pack -u ytconvertv2 -v ${{ steps.version.outputs.full_without_prefix }} -p .\ReleasePrep\ -e ytconvertv2.exe --delta None
    #             vpk upload github -o .\Releases\ --repoUrl https://github.com/${{ github.repository }} --pre --merge --token ${{ secrets.GITHUB_TOKEN }}
                